file-version: 6

# Server configs - These are settings you need to change!
# The name of the limbo server in your velocity network
limbo-name: limbo # Default "limbo"

# Direct-connect-server is the name of the server you want players to connect to if they connected directly to the server in the velocity network
direct-connect-server: lobby # Default "lobby"

# How often the server should check if it can connect
task-interval: 3000 # The time in milliseconds (Default: 3000)

# How often should the user be notified of their position in the queue
queue-enabled: true # Should players be reconnected through a queue (Default: true)
queue-notify-interval: 30 # The time in seconds (Default: 30)

# A list of disabled commands, which will not work inside the Limbo server. Recommended commands are ones that the player can use to transfer server, like /server or /hub
disabled-commands: ["server", "lobby", "hub"]
